isUpperCase
Jinglong7/validate pull request #5
Opened 2020-09-30 14:39 UTC by hamptonmoore

2020-10-01 16:10 UTC, Bunlong requested changes

2020-10-01 16:10 UTC, Bunlong commented on src/libs/isUpperCase.ts
> +};
@hamptonmoore Please add newline at end of file as there is a warning following.

![Screenshot from 2020-10-01 23-09-20](https://user-images.githubusercontent.com/1308397/94834874-25e0c080-043b-11eb-85ee-8cf79d8124cc.png)

2020-10-04 16:43 UTC, hamptonmoore commented
The issue has been fixed

2020-10-05 01:32 UTC, Bunlong approved these changes

2020-10-05 01:32 UTC, merged